# Generated by Django 3.0.4 on 2020-03-25 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
